### PR TITLE
Disable readonly property before deleting files

### LINKED ISSUE #614: Possible wrong implementation of `RenameAndMerge` in `(pre)updateexec` scripts
https://github.com/CnCNet/xna-cncnet-client/commit/fc939a06ff978b51daa6563eaa15a28cf48319ec#diff-0d2ea0a16eec1c4752818efaced94ca47df0f506a743e4407f0f6d667ac5daa0R894

图片

### PR DESCRIPTION
**Pull request by SadPencil**
Also, fixes #614

### CODE REVIEW

File: ClientUpdater/Updater.cs [hunk 1]
```diff
@@ -851,7 +855,13 @@ private static void ExecuteScript(string fileName)
...
             try
             {
-                SafePath.DeleteFileIfExists(GamePath, key);
+                FileInfo fileInfo = SafePath.GetFile(GamePath, key);
+
+                if (fileInfo.Exists)
+                {
+                    fileInfo.IsReadOnly = false;
+                    fileInfo.Delete();
+                }
```
Comment (MahBoiDeveloper) [inline ClientUpdater/Updater.cs:864]: Instead of constantly checking `IsReadOnly` before deleting, it is better to modify the Rampastring.Tools class `SafePath` to support disabling the read-only property in delete methods.

**Review by MahBoiDeveloper — APPROVED** [review]

File: ClientUpdater/Updater.cs (hunk 1 above)
Comment (SadPencil) [reply ClientUpdater/Updater.cs:864]: I agree but let's deal with the emergency first

**Comment by MahBoiDeveloper** [comment]
Changes doesn't have a negative effect on 2nd stage updater and client.
